apiVersion: v1
kind: PersistentVolume
metadata:
  name: task-pv-volume
  # 这里指定一下namespace
  namespace: spark-operator
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    # 自定义本地路径
    path: "/root/k8s-storage1/mnt"
