apiVersion: v1
kind: PersistentVolume
metadata:
  name: task-pv-volume
  namespace: spark-operator
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 10Gi
  nfs:
    path: /nfs/spark-operator-data
    server: 10.0.0.7
  storageClassName: nfs-storage
  volumeMode: Filesystem
