apiVersion: v1
kind: Service
metadata:
  labels:
    name: sparkit-api
  name: sparkit-api-service
  namespace: spark-operator
spec:
  clusterIP: 10.108.196.204
  ports:
  - name: sparkit-api
    port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    name: sparkit-api
  sessionAffinity: None
  type: ClusterIP